name: Build and Upload Docker Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (Optional) Set up Docker Buildx for faster builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Lowercase Repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "${GITHUB_ENV}"

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: unleash-server/Dockerfile
          push: true
          # Use buildx if set up, otherwise use the default Docker build
          builder: ${{ steps.buildx.outputs.name || 'default' }}
          tags: ghcr.io/${{ env.REPO }}:latest
          cache-from: type=gha  # Enable layer caching
          cache-to: type=gha,mode=max
