name: Build and Upload Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t unleash-server unleash-server/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag unleash-server ghcr.io/${{ github.repository_owner }}/unleash-server:${{ github.sha }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/unleash-server:${{ github.sha }}
